name: run advent of code

on: [push]


jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache nimble
        id: cache-nimble
        uses: actions/cache@v1
        with:
          path: ~/.nimble
          key: ${{ runner.os }}-nimble-${{ hashFiles('*.nimble') }}
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: '1.6.x'
      - run: nimble build -Y
      - run: nimble test -Y
      - run: |
          nimble install -Y
          ./aoc2022
